### ISSUE TITLE
error: LNK2019 无法解析qtng::FileLike::~FileLike

### ISSUE THREAD

**Issue by liuaifu** [hgoldfish/qtnetworkng#11]
qtnetworkng.lib(socket_utils.obj):-1: error: LNK2019: 无法解析的外部符号 "public: virtual __thiscall qtng::FileLike::~FileLike(void)" (??1FileLike@qtng@@UAE@XZ)，该符号在函数 "public: virtual __thiscall qtng::SocketLike::~SocketLike(void)" (??1SocketLike@qtng@@UAE@XZ) 中被引用

环境：VS2017 + QT5.13.1

**Comment by hgoldfish** [comment]
I can't reproduce this bug. Are you using the latest version?

**Comment by hgoldfish** [comment]
ok, i've push the commit which fixes the missing of file `kcp.cpp`.
