### ISSUE TITLE
在mac电脑上编译examples/http_get_cmake失败

### ISSUE THREAD

**Issue by lianhansheng** [hgoldfish/qtnetworkng#16]
编译错误：
![image](https://user-images.githubusercontent.com/1023339/115044382-0bb68d80-9f08-11eb-86d2-9d13608b2d8f.png)
修改方案：
![image](https://user-images.githubusercontent.com/1023339/115044796-6fd95180-9f08-11eb-8955-fa0491bcf6e9.png)

**Comment by hgoldfish** [comment]
pull request merged
