### ISSUE TITLE
I failed to compile under win10. 

### ISSUE THREAD

**Issue by liuxiandeng** [hgoldfish/qtnetworkng#25]
I failed to compile under win10. 

The error is “The error is "eventloop_win.obj:-1: error: LNK2019: Unresolved external symbol __imp_TranslateMessage, which is in the function "public: virtual void __cdecl qtng::WinEventLoopCoroutinePrivate::run(void)" (?run@WinEventLoopCoroutinePrivate@qtng @@UEAAXXZ) is quoted in ”. 

My QT version is 5.13.1, and the MSVC version is 2017 64bit. The minimal project inherits Qmainwindow, and then integrates Qtnetworkng.I did not implement my own function or code. It can compile successfully under Linux, but it fails under Win10.

**Comment by hgoldfish** [comment]
I seems that the linker can not find user32.lib. Maybe you are using a Qt build incompatible with msvc2017. 

You might check your QtCreator's Kits configure, and make sure the IDE can build other plain Qt applications.

**Comment by hgoldfish** [comment]
It seems that the linker miss user32.lib while using qmake with msvc.

I've fixed that problem.

Attention: qtng does not support ssl and https by default if you are using qmake.

**Comment by liuxiandeng** [comment]
Thank you hgoldfish,I solved this problem.

I added a line of code to qtnetworkng.pri: LIBS += -luser32, the position is on the next line of LIBS += -lws2_32 

Thank you
