### ISSUE TITLE
How to use timer?

### ISSUE THREAD

**Issue by ywwyewenwei** [hgoldfish/qtnetworkng#54]

**Comment by hgoldfish** [comment]
There is no need to use QTimer in coroutines, just call `Coroutine::sleep()` or `Coroutine::msleep()` instead:

    Coroutine::spawn([] {
        while (true) {
            qDebug()<< "hello, there!";
            Coroutine::sleep(1.0);    // or msleep(1000);
        }
    });

**Comment by ywwyewenwei** [comment]
Thanks a lot.
